name: build-deploy-qa
on:
  release:
    types: [prereleased]

jobs:
  deploy_qa:
    name: "Run Tests"
    runs-on: ubuntu-18.04
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - run: echo "Running build and test for ${{ github.ref }} branch"

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Docker Image Version
        id: "determine-tag"
        run: "echo \"::set-output name=tag::${GITHUB_REF#refs/tags/}\""

      - run: echo ${{ steps.determine-tag.outputs.tag }}

      - name: Build project
        run: make docker/build

      - name: Running lint/bandit/check-packages
        run: make docker/verify

      - name: Running test
        run: make docker/test
